### PR TITLE
Settings page

### PR DESCRIPTION
**Pull request by bethelju**
[Trello Card](https://trello.com/c/s1nP0M66/19-setting-pages-ui)

What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
Adds a setting page with a stub user, see below!

What is the current behavior? (You can also link to an open issue here)
There is no settings page

What is the new behavior? (if this is a feature change)
Adding a settings page at the /settings route according to the Figma Design. This was completed by:
1) Adding a profile picture component
2) Adding a component for the settings page with corresponding CSS module
3) Adding a stub user for testing purposes

Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)
No 

Discussion Questions
Should we use Typescript in the same way that we've been using for the React Native repo? Might be wise to decide closer to the beginning of the project to minimize pain down the road

Images (before/ after screenshots, interaction GIFs, ...)
Imgur

Figma Design
Figma

TODO
May make sense to shrink a tad

### CODE REVIEW

**Review by asengelhart — COMMENTED** [review]
Some thoughts that are coming to mind:

1. I don't know if we would ever want to add a separate Settings component beyond the settings page, but just in case we should consider naming the component SettingsPage.  My forthcoming LoginPage component will follow that naming convention for that reason.

2. We shouldn't even be able to request the actual password from the backend, so anything we display in the Password field should be the same for all users (so maybe just place `********` in that `div` rather than any actual code).

3. As a topic of conversation, we should probably discuss how we want to handle password changes in general for this - would it work better to be able to change your password on the screen or have a separate page for that?

4. I'll actually be sending a PR for some helper methods for handling API calls and storing user credentials, so be on the lookout for that - they'll certainly be useful for this action.

**Comment by bethelju** [comment]
Hi Alex! Thanks for the useful feedback. Here are my thoughts:
1. 100% agree. I've added a commit to change the name to SettingsPage as above. 
2. Yeah, I'm not really sure how we want to handle this. If we have a set number of asterisks rather than a number that reflects the length of the password, it could confuse the user. On the other hand, getting the length of the user password sent to us from the backend (in the same call that we get user information like name, role, etc.) might be a bit more complicated. I'm not 100% sure what encrypting algorithm we use on the backend and if we would even be able to extract the length of the password from that. For the pre-alpha, setting a set number of asterisks is probably best.
3. For the future, it might be the best user experience if the user is able to change the password from the same page. We could control this by holding state within the page that keeps track of if the 'Update' Button has been pressed, and conditionally render a div or input component based upon that.
4. Fantastic! Thanks for taking care of that.

**Review by asengelhart — APPROVED** [review]
Looks good so far!

**Review by tackc — APPROVED** [review]
Looks good! Thanks for your work on this component 😀

**Pull request merged**
